CREATE DATABASE DVH1621050875
GO
USE DVH1621050875
GO

CREATE TABLE Person(
	PersonId VARCHAR(20) PRIMARY KEY,
	PersonName NVARCHAR(50) NOT NULL
)

CREATE TABLE Student(
	PersonId VARCHAR(20) PRIMARY KEY,
	PersonName NVARCHAR(50) NOT NULL,
	University NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(50) NOT NULL,
)

CREATE TABLE Lecture(
	PersonId VARCHAR(20) PRIMARY KEY,
	PersonName NVARCHAR(50) NOT NULL,
	Faculty NVARCHAR(50) NOT NULL,
	Department NVARCHAR(50) NOT NULL,
)
